channels:
  - conda-forge
  - bioconda
  - r
  - defaults
dependencies:
  - python=3.5.1
  - snakemake=3.11.0
  - pyyaml=3.11
  - biopython=1.69
  - java-jdk=8.0.112
  - graphviz=2.38.0
  - xorg-libxrender
  - xorg-libxpm
